plugin:
  image: krates/ipam-plugin:${VERSION}
  net: host
  log_driver: journald
  volumes:
    - "./:/app"
    - "/run/docker/plugins/:/run/docker/plugins/"
    - "/var/run/docker.sock:/var/run/docker.sock"
etcd:
  image: krates/etcd:2.3.7
  log_driver: journald
  net: host